name: Workshop Update

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install 32-bit binaries
        run: sudo apt install lib32gcc1 lib32stdc++6

      - name: Set binary permissions
        run: chmod -R +x .github/bin/

      - name: Convert to GMA
        run: .github/bin/gmad_linux create -folder $PWD -out "$PWD/addon.gma"

      - name: Publish GMA
        run: .github/bin/gmodws ${{ secrets.ACCOUNT_NAME }} ${{ secrets.ADDON_ID }} "$PWD/addon.gma"
        env:
          STEAM_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}