name: Publish to workshop

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install 32-bit binaries
        run: sudo apt install lib32gcc1 lib32stdc++6

      - name: Convert to GMA
        run: ./.github/bin/gmad_linux create -folder $PWD -out "$PWD/addon.gma"

      - name: test
        run: ls -la